### ISSUE TITLE
After commenting there are 2 comments displayed.

### ISSUE THREAD

**Issue by mschaaf** [Dica-Developer/gh-review#101]
It seems it is only a displaying issue because on github is only one shown.

**Comment by JayGray** [comment]
Cannot reproduce.
Please reopen if it happens again.

**Comment by mschaaf** [comment]
Interesting is after I deleted one of them bothe were removed, so it seems
it was a displaying issue.

2015-03-18 21:44 GMT+01:00 Jörg Weber <notifications@github.com>:
