### ISSUE TITLE
Line Comments not working on special lines

### ISSUE THREAD

**Issue by mfuhrmeisterDM** [Dica-Developer/gh-review#111]
If you want to create a comment on a line like this:
`... ... @@ -1012,8 +895,6 @@ public void test()`

this leads into a js error:
`Invalid value for parameter "line": ... is NaN`.

**Comment by JayGray** [comment]
@mfuhrmeisterDM 
As this line, you mentioned, is not part of an actual commit it is a bug that it is possible to
add a comment. I would disable comment functionality for commit chunk header lines.

**Comment by mfuhrmeisterDM** [comment]
thx
